from .base import generate_functions
from .video_general import VIDEO_GENERAL_QUERY_DEFINITIONS
from .video_creator import VIDEO_CREATOR_QUERY_DEFINITIONS
from .views_dynamics import VIEWS_DYNAMICS_QUERY_DEFINITIONS
from .engagement import ENGAGEMENT_QUERY_DEFINITIONS
from .advanced import ADVANCED_QUERY_DEFINITIONS

QUERY_DEFINITIONS = {
    **VIDEO_GENERAL_QUERY_DEFINITIONS,
    **VIDEO_CREATOR_QUERY_DEFINITIONS,
    **VIEWS_DYNAMICS_QUERY_DEFINITIONS,
    **ENGAGEMENT_QUERY_DEFINITIONS,
    **ADVANCED_QUERY_DEFINITIONS,
}

FUNCTIONS = generate_functions(QUERY_DEFINITIONS)
